version: '3.7'
services:
  php:
    container_name: php-fraud
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/:cached
    networks:
      - php

networks:
  php:
